apiVersion: v1
kind: Service
metadata:
  name: model-player
  labels:
    app: redis
    role: master
    tier: backend
spec:
  type: NodePort
  ports:
  - name: model-player
    port: 5000
  selector:
    app: redis
    role: master
    tier: backend
