apiVersion: v1
kind: Service
metadata:
  name: model-player
  labels:
    app: redis
    role: master
    tier: backend
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: redis
    role: master
    tier: backend
