apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: model-player
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: model-player
        image: tobegit3hub/model-player
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5000
